name: Docker Build & Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Login to DockerHub (если нужно)
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t crmsystem-api .

    - name: Save Docker image to file
      run: docker save crmsystem-api -o crmsystem-api.tar

    - name: Copy image to AWS EC2 (пример)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "crmsystem-api.tar"
        target: "~/"

    - name: SSH and run Docker container on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker load -i ~/crmsystem-api.tar
          docker stop crmsystem-api || true && docker rm crmsystem-api || true
          docker run -d -p 80:80 --name crmsystem-api crmsystem-api